name: 触发部署

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 触发 Netlify / Vercel / Github 构建钩子
        run: |
            # curl -X POST https://api.netlify.com/build_hooks/6878a62634e95e4fb0b4e87e
            # curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_6KNxQQx6d8cYPOdysNTNdjO8bxpz/LvfmIyLh2J